import os
os.system('pip3 install speechrecognition')
os.system('pip3 install wikipedia')
os.system('pip3 install googletrans')
os.system('pip3 install persiantools')
os.system('pip3 install khayyam')
os.system('pip3 install mpyg321')
os.system('pip3 install mutagen')
os.system('pip3 install feedparser')
os.system('pip3 install mysql.connector')
os.system('pip3 install requests')
os.system('pip3 install bs4')
os.system('pip3 install math')
os.system('pip3 install numpy')
os.system('pip3 install csv')
os.system('pip3 install forecastiopy')
os.system('pip3 install imp')
os.system('pip3 install pexpect')
os.system('sudo apt-get install mpg321')
os.system('sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0')
os.system('pip3 install pyaudio')
#os.system('sudo apt-get install flac') #PulseAudio
#os.system('sudo apt-get install swig')
#os.system('sudo apt-get install pocketsphinx')
#os.system('sudo apt-get install python-pocketsphinx')
#os.system('sudo apt-get install libpulse-dev --yes')
#os.system(' pip3 install pocketsphinx')
